In [16]:
import pandas as pd
pd.set_option('display.max_columns', False)
import warnings
warnings.filterwarnings('ignore')

df = pd.DataFrame(pd.read_excel("./data/Telco_customer_churn.xlsx"))
df1 = pd.DataFrame(pd.read_excel("./data/Telco_customer_churn_demographics.xlsx"))
df2 = pd.DataFrame(pd.read_excel("./data/Telco_customer_churn_location.xlsx")) 
df3 = pd.DataFrame(pd.read_excel("./data/Telco_customer_churn_population.xlsx")) 
df4 = pd.DataFrame(pd.read_excel("./data/Telco_customer_churn_services.xlsx")) 
df5 = pd.DataFrame(pd.read_excel("./data/Telco_customer_churn_status.xlsx")) 
df6 = pd.DataFrame(pd.read_csv("./data/Address.csv"))

In [17]:
merged_df = pd.merge(df1, df2[['Customer ID','Country','State','City','Zip Code','Latitude','Longitude']], on='Customer ID', how='inner')
merged_df = pd.merge(merged_df, df6[['Customer ID', 'address']], on='Customer ID', how='inner')
merged_df = pd.merge(merged_df, df3, on='Zip Code', how='inner')
#merged_df = pd.merge(merged_df, df3, on='Customer ID', how='inner')
merged_df = pd.merge(merged_df, df4, on='Customer ID', how='inner')
merged_df = pd.merge(merged_df, df5[['Customer ID', 'Satisfaction Score','Customer Status','Churn Label','Churn Value','Churn Score','CLTV','Churn Category','Churn Reason']], on='Customer ID', how='inner')

In [18]:
merged_df.head(2)

  Customer ID  Count_x Gender  Age  ... Churn Score  CLTV Churn Category                  Churn Reason
0  8779-QRDMV        1   Male   78  ...          91  5433     Competitor  Competitor offered more data
1  4737-AQCPU        1   Male   39  ...          42  4658            NaN                           NaN

[2 rows x 55 columns]

In [19]:
merged_df.drop(['Count_x','Count_y'], axis=1, inplace=True)
# Drop columns at index 1 and 3
#df = df.drop(df.columns[[1, 3]], axis=1)
merged_df.head(2)

  Customer ID Gender  Age Under 30  ... Churn Score  CLTV Churn Category                  Churn Reason
0  8779-QRDMV   Male   78       No  ...          91  5433     Competitor  Competitor offered more data
1  4737-AQCPU   Male   39       No  ...          42  4658            NaN                           NaN

[2 rows x 53 columns]

In [21]:
merged_df.to_excel('./data/Merged Churn File.xlsx', sheet_name='Sheet1', index=False)

Data Description
7043 observations with 33 variables

CustomerID: A unique ID that identifies each customer.

Count: A value used in reporting/dashboarding to sum up the number of customers in a filtered set.

Country: The country of the customer’s primary residence.

State: The state of the customer’s primary residence.

City: The city of the customer’s primary residence.

Zip Code: The zip code of the customer’s primary residence.

Lat Long: The combined latitude and longitude of the customer’s primary residence.

Latitude: The latitude of the customer’s primary residence.

Longitude: The longitude of the customer’s primary residence.

Gender: The customer’s gender: Male, Female

Senior Citizen: Indicates if the customer is 65 or older: Yes, No

Partner: Indicate if the customer has a partner: Yes, No

Dependents: Indicates if the customer lives with any dependents: Yes, No. Dependents could be children, parents, grandparents, etc.

Tenure Months: Indicates the total amount of months that the customer has been with the company by the end of the quarter specified above.

Phone Service: Indicates if the customer subscribes to home phone service with the company: Yes, No

Multiple Lines: Indicates if the customer subscribes to multiple telephone lines with the company: Yes, No

Internet Service: Indicates if the customer subscribes to Internet service with the company: No, DSL, Fiber Optic, Cable.

Online Security: Indicates if the customer subscribes to an additional online security service provided by the company: Yes, No

Online Backup: Indicates if the customer subscribes to an additional online backup service provided by the company: Yes, No

Device Protection: Indicates if the customer subscribes to an additional device protection plan for their Internet equipment provided by the company: Yes, No

Tech Support: Indicates if the customer subscribes to an additional technical support plan from the company with reduced wait times: Yes, No

Streaming TV: Indicates if the customer uses their Internet service to stream television programing from a third party provider: Yes, No. The company does not charge an additional fee for this service.

Streaming Movies: Indicates if the customer uses their Internet service to stream movies from a third party provider: Yes, No. The company does not charge an additional fee for this service.

Contract: Indicates the customer’s current contract type: Month-to-Month, One Year, Two Year.

Paperless Billing: Indicates if the customer has chosen paperless billing: Yes, No

Payment Method: Indicates how the customer pays their bill: Bank Withdrawal, Credit Card, Mailed Check

Monthly Charge: Indicates the customer’s current total monthly charge for all their services from the company.

Total Charges: Indicates the customer’s total charges, calculated to the end of the quarter specified above.

Churn Label: Yes = the customer left the company this quarter. No = the customer remained with the company. Directly related to Churn Value.

Churn Value: 1 = the customer left the company this quarter. 0 = the customer remained with the company. Directly related to Churn Label.

Churn Score: A value from 0-100 that is calculated using the predictive tool IBM SPSS Modeler. The model incorporates multiple factors known to cause churn. The higher the score, the more likely the customer will churn.

CLTV: Customer Lifetime Value. A predicted CLTV is calculated using corporate formulas and existing data. The higher the value, the more valuable the customer. High value customers should be monitored for churn.

Churn Reason: A customer’s specific reason for leaving the company. Directly related to Churn Category.